### ISSUE TITLE
Eu, como usuário, desejo ter total controle sobre meu acesso à aplicação para minha segurança

### ISSUE THREAD

**Issue by guigawiller** [Requisitos-2017-2/Grupo06#5]
- [ ] O usuário deve poder conectar-se.
- [ ] O usuário deve poder conectar-se pelo Facebook.
- [ ] O usuário deve poder registar-se.
- [ ] O usuário deve poder desconectar-se.
